### ISSUE TITLE
error when loading flat files

### ISSUE THREAD

**Issue by jamesday76** [vanessa-king/UBC_LAIR#167]
When using LD01A (Load-Data-01-A) on .Z_flat or .I(V)_flat files, the error message below appears. The problem is tripped in the LoadData function, and the otherwise block should handle cases where no appropriate file type is selected, but something seems to prevent the control from reaching the switch statement (or if the file type is one of the unhandled cases), and so commentC remains unassigned. Maybe we can initialize commentC to a default value before the switch block?

Error message:
Output argument "commentC" (and possibly others) not assigned a value in the execution with "loadData" function.

Error in mainTrunk (line 144)
[data, commentA, commentB, commentC] = loadData(data);

**Comment by m-altthaler** [comment]
see changes in #181 
added a comment for .Z_flat, .I(V)_flat, .dat files that they are not yet supported - but it's work in progress. 
Note these are treated under otherwise as there were cases for them (which used to be empty). Now a displayed message and commentC are assigned within the respective case

**Comment by vanessa-king** [comment]
This merge has been approved - it sounds like we can close this issue. Agreed?

**Comment by m-altthaler** [comment]
I think this one should be closed yes. We should have another one related to actually implementing the loading functions of 'flat' files
